### ISSUE TITLE
Inconsistent Game Mode Image Naming Convention

### ISSUE THREAD

**Issue by trevor-lambert** [Brawlify/CDN#10]
## Current Situation
The Brawl Stars API provides only game mode names, making CDN game mode image retrieval difficult.

The current file names for game mode images do not correspond to the game mode names returned by the the Brawl Stars API. This creates several challenges:

- Difficult to programmatically match game modes to images
- Manual mapping required to associate game modes with their correct images

## Proposed Solution
Rename CDN image files to directly reflect the game mode names returned by the API:

### Example for Gem Grab
- Current: `CDN/game-modes/regular/48000000.png`
- Proposed: `CDN/game-modes/regular/gem-grab.png`

### Benefits
- Simplified image matching process
- More intuitive and predictable image naming

## Recommended Implementation
1. Audit current game mode images
2. Create a mapping of current arbitrary names to game mode names
3. Rename images to follow the `{game-mode-name}.png` naming convention

**Comment by Henrylq** [comment]
I would recommend looking up map ids instead of relying on game mode names from the official API. Check the [locations](https://api.brawlify.com/game/csv_logic/locations) file, then take the map's **GameModeVariation** value, then look it up in [game_mode_variations](https://api.brawlify.com/game/csv_logic/game_mode_variations) to get the ID.

I know this is a bit of work, but some game modes often get their names changed on updates and this isn't always updated in the API. Some game modes in the official API, like showdown, don't always point to the correct showdown, so pointing to icons by their appropriate IDs depending on the map works the best way in my opinion, it's just harder to do.

Hope this works! Sorry for the late response, this also isn't what you hoped for, but hopefully it makes sense!
